#!/bin/sh

# delete keytab
rm -rf hdfs.keytab | rm -rf yarn.keytab | rm -rf mapred.keytab
ssh hd-c1nn rm -rf /etc/hadoop/conf/hdfs.keytab | rm -rf /etc/hadoop/conf/yarn.keytab | rm -rf /etc/hadoop/conf/mapred.keytab
ssh hd-c2nn rm -rf /etc/hadoop/conf/hdfs.keytab | rm -rf /etc/hadoop/conf/yarn.keytab | rm -rf /etc/hadoop/conf/mapred.keytab
ssh hd-c1dn1 rm -rf /etc/hadoop/conf/hdfs.keytab | rm -rf /etc/hadoop/conf/yarn.keytab | rm -rf /etc/hadoop/conf/mapred.keytab
ssh hd-c1dn2 rm -rf /etc/hadoop/conf/hdfs.keytab | rm -rf /etc/hadoop/conf/yarn.keytab | rm -rf /etc/hadoop/conf/mapred.keytab
ssh hd-c2dn2 rm -rf /etc/hadoop/conf/hdfs.keytab | rm -rf /etc/hadoop/conf/yarn.keytab | rm -rf /etc/hadoop/conf/mapred.keytab
ssh hd-c2dn1 rm -rf /etc/hadoop/conf/hdfs.keytab | rm -rf /etc/hadoop/conf/yarn.keytab | rm -rf /etc/hadoop/conf/mapred.keytab
ssh pdi-n1 rm -rf /etc/hadoop/conf/hdfs.keytab | rm -rf /etc/hadoop/conf/yarn.keytab | rm -rf /etc/hadoop/conf/mapred.keytab

# destroy authen
kdestroy
ssh hd-c1nn kdestroy
ssh hd-c2nn kdestroy
ssh hd-c1dn1 kdestroy
ssh hd-c1dn2 kdestroy
ssh hd-c2dn2 kdestroy
ssh hd-c2dn1 kdestroy
ssh pdi-n1 kdestroy
ssh hd-c1nn sudo -u hdfs kdestroy
ssh hd-c2nn sudo -u hdfs kdestroy
ssh hd-c1dn1 sudo -u hdfs kdestroy
ssh hd-c1dn2 sudo -u hdfs kdestroy
ssh hd-c2dn1 sudo -u hdfs kdestroy
ssh hd-c2dn2 sudo -u hdfs kdestroy
ssh pdi-n1 sudo -u hdfs kdestroy
