## MYSQL PASSWORD
set @PASSWD := 'Traceon1234!';

## CREATE DATABASE
CREATE SCHEMA `scm` DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_general_ci;
CREATE SCHEMA `amon` DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_general_ci;
CREATE SCHEMA `rman` DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_general_ci;
CREATE SCHEMA `hue` DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_general_ci;
CREATE SCHEMA `metastore` DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_general_ci;
CREATE SCHEMA `sentry` DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_general_ci;
CREATE SCHEMA `nav` DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_general_ci;
CREATE SCHEMA `navms` DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_general_ci;
CREATE SCHEMA `oozie` DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_general_ci;


## CREATE USER
CREATE USER 'cloudera'@'localhost' IDENTIFIED BY @PASSWD;
CREATE USER 'cloudera'@'%' IDENTIFIED BY @PASSWD;
CREATE USER 'scm'@'localhost' IDENTIFIED BY @PASSWD;
CREATE USER 'scm'@'%' IDENTIFIED BY @PASSWD;
CREATE USER 'amon'@'localhost' IDENTIFIED BY @PASSWD;
CREATE USER 'amon'@'%' IDENTIFIED BY @PASSWD;
CREATE USER 'rman'@'localhost' IDENTIFIED BY @PASSWD;
CREATE USER 'rman'@'%' IDENTIFIED BY @PASSWD;
CREATE USER 'hue'@'localhost' IDENTIFIED BY @PASSWD;
CREATE USER 'hue'@'%' IDENTIFIED BY @PASSWD;
CREATE USER 'hive'@'localhost' IDENTIFIED BY @PASSWD;
CREATE USER 'hive'@'%' IDENTIFIED BY @PASSWD;
CREATE USER 'sentry'@'localhost' IDENTIFIED BY @PASSWD;
CREATE USER 'sentry'@'%' IDENTIFIED BY @PASSWD;
CREATE USER 'nav'@'localhost' IDENTIFIED BY @PASSWD;
CREATE USER 'nav'@'%' IDENTIFIED BY @PASSWD;
CREATE USER 'navms'@'localhost' IDENTIFIED BY @PASSWD;
CREATE USER 'navms'@'%' IDENTIFIED BY @PASSWD;
CREATE USER 'oozie'@'localhost' IDENTIFIED BY @PASSWD;
CREATE USER 'oozie'@'%' IDENTIFIED BY @PASSWD;



## GRANT PRIVILEGES
GRANT ALL ON *.* TO 'cloudera'@'%' IDENTIFIED BY @PASSWD;
GRANT ALL ON *.* TO 'cloudera'@'localhost' IDENTIFIED BY @PASSWD;
GRANT ALL PRIVILEGES ON metastore.* TO 'scm'@'localhost' IDENTIFIED BY @PASSWD;
GRANT ALL PRIVILEGES ON metastore.* TO 'scm'@'%' IDENTIFIED BY @PASSWD;
GRANT ALL PRIVILEGES ON amon.* TO 'amon'@'localhost' IDENTIFIED BY @PASSWD;
GRANT ALL PRIVILEGES ON amon.* TO 'amon'@'%' IDENTIFIED BY @PASSWD;
GRANT ALL PRIVILEGES ON rman.* TO 'rman'@'localhost' IDENTIFIED BY @PASSWD;
GRANT ALL PRIVILEGES ON rman.* TO 'rman'@'%' IDENTIFIED BY @PASSWD;
GRANT ALL PRIVILEGES ON *.* TO 'hue'@'localhost' IDENTIFIED BY @PASSWD;
GRANT ALL PRIVILEGES ON *.* TO 'hue'@'%' IDENTIFIED BY @PASSWD;
GRANT ALL PRIVILEGES ON metastore.* TO 'hive'@'localhost' IDENTIFIED BY @PASSWD;
GRANT ALL PRIVILEGES ON metastore.* TO 'hive'@'%' IDENTIFIED BY @PASSWD;
GRANT ALL PRIVILEGES ON sentry.* TO 'sentry'@'localhost' IDENTIFIED BY @PASSWD;
GRANT ALL PRIVILEGES ON sentry.* TO 'sentry'@'%' IDENTIFIED BY @PASSWD;
GRANT ALL PRIVILEGES ON nav.* TO 'nav'@'localhost' IDENTIFIED BY @PASSWD;
GRANT ALL PRIVILEGES ON nav.* TO 'nav'@'%' IDENTIFIED BY @PASSWD;
GRANT ALL PRIVILEGES ON navms.* TO 'navms'@'localhost' IDENTIFIED BY @PASSWD;
GRANT ALL PRIVILEGES ON navms.* TO 'navms'@'%' IDENTIFIED BY @PASSWD;
GRANT ALL PRIVILEGES ON oozie.* TO 'oozie'@'localhost' IDENTIFIED BY @PASSWD;
GRANT ALL PRIVILEGES ON oozie.* TO 'oozie'@'%' IDENTIFIED BY @PASSWD;

FLUSH PRIVILEGES;
